# Generated by Django 3.0.3 on 2020-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
